/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centre_libraly;


import Java_class.BooksManage;
import Java_class.Genres;
import Java_class.Member;
import Java_class.function_java;
import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


/**
 *
 * @author HP
 */
public class AddBookForm extends javax.swing.JFrame {
    
    static String imagePath = "";
    static int id_auth;
    
    Member member = new Member();
    function_java func = new function_java();
    Genres genre = new Genres();
    HashMap<String, Integer> genreMap = genre.getGenreMap();
    /**
     * Creates new form MannaegBooks
     */
    Java_class.Authors AuthorInstance = new Java_class.Authors();
    
    public AddBookForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(0,153,153));
        MainPanel.setBorder(panelHeaderBorder);
        func.displayImage(50, 50, "image/book_head.png", Title_Authors);

        
        //table to show data
      fillJcomboBoxWithGenre();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Title_Authors = new javax.swing.JLabel();
        jLabel1_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1_add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Book_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        book_publisher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        image_cover = new javax.swing.JLabel();
        Book_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        book_description = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1_add1 = new javax.swing.JButton();
        book_genre = new javax.swing.JComboBox<>();
        book_Quantity = new javax.swing.JSpinner();
        jButton1_add2 = new javax.swing.JButton();
        book_price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        book_auth = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser_recieve = new com.toedter.calendar.JDateChooser();
        genre_id = new javax.swing.JLabel();
        jButton1_add3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        Title_Authors.setBackground(new java.awt.Color(0, 153, 153));
        Title_Authors.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_Authors.setForeground(new java.awt.Color(255, 255, 255));
        Title_Authors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Authors.setText("Add Book");
        Title_Authors.setOpaque(true);

        jLabel1_exit.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_exit.setText("x");
        jLabel1_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_exit.setOpaque(true);
        jLabel1_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_exitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Book's Name");
        jLabel2.setToolTipText("");

        jButton1_add.setText("Add");
        jButton1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Authors:");
        jLabel3.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Genre:");
        jLabel5.setToolTipText("");

        book_publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_publisherActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel6.setText("Publisher:");
        jLabel6.setToolTipText("");

        image_cover.setBackground(new java.awt.Color(204, 204, 204));
        image_cover.setOpaque(true);
        image_cover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image_coverMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("Book's ID:");
        jLabel4.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel7.setText("Quantity:");
        jLabel7.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel9.setText("Date's Recieve:");
        jLabel9.setToolTipText("");

        book_description.setColumns(20);
        book_description.setRows(5);
        jScrollPane1.setViewportView(book_description);

        jLabel10.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel10.setText("Book's Cover");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel11.setText("Book's decription");
        jLabel11.setToolTipText("");

        jButton1_add1.setText("Cancel");
        jButton1_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add1ActionPerformed(evt);
            }
        });

        book_genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default" }));
        book_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_genreActionPerformed(evt);
            }
        });

        jButton1_add2.setBackground(new java.awt.Color(51, 51, 51));
        jButton1_add2.setForeground(new java.awt.Color(0, 102, 102));
        jButton1_add2.setText("select picture");
        jButton1_add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add2ActionPerformed(evt);
            }
        });

        book_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_priceActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("Price:");
        jLabel8.setToolTipText("");

        jButton1.setText("select author");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        genre_id.setText("ID");

        jButton1_add3.setText("Clear");
        jButton1_add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addComponent(Book_name)
                                .addGap(364, 364, 364))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(Book_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book_price, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jDateChooser_recieve, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(168, 168, 168)
                                        .addComponent(jButton1_add2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(book_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(book_auth, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(genre_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(157, 157, 157)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(Title_Authors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(image_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addContainerGap(41, Short.MAX_VALUE)
                        .addComponent(jButton1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1_add3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title_Authors, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Book_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Book_name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(book_auth)
                                    .addComponent(jButton1))))
                        .addGap(31, 31, 31)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(book_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genre_id)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(book_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(book_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(book_price, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jDateChooser_recieve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(image_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_add2)))
                .addGap(57, 57, 57)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_add3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_exitMouseClicked
        // TODO add your handling code here:
        DasboardForm dash  = new DasboardForm();
        this.dispose();
        
    }//GEN-LAST:event_jLabel1_exitMouseClicked

    
    private void jButton1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addActionPerformed
        
       String book_id = Book_ID.getText();
        if(!verify())
        {
           JOptionPane.showMessageDialog(null, "one or more fields are empty ", "empty data", 2);
        }else if(BooksManage.isBook_ID_EXIST(book_id))
        {
            JOptionPane.showMessageDialog(null, "there are already this id is exist", "empty id", 2);
        }
        else{
        try {
           
           String book_name = Book_name.getText();
           Integer book_aut = id_auth;
           Integer book_genr = Integer.parseInt(genre_id.getText());
           String B_publisher = book_publisher.getText();
           int Quantity = Integer.parseInt(book_Quantity.getValue().toString());
           Double price = Double.parseDouble(book_price.getText());
           String description = book_description.getText();
           SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
           String b_recieve_date = dateFormat.format(jDateChooser_recieve.getDate());
            byte[] img = Files.readAllBytes(Paths.get(imagePath));
            BooksManage bookMNG = new BooksManage();
            bookMNG.addBook(book_id, book_name, book_aut, book_genr, B_publisher, Quantity, price,b_recieve_date,description,img);
        } catch (IOException ex) {
             System.out.println("IOException");
        } catch(NumberFormatException e){
            System.out.println("numberformat exceptioin");
        }
        }  
 
    }//GEN-LAST:event_jButton1_addActionPerformed

    private void book_publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_publisherActionPerformed

    private void image_coverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_coverMouseClicked
        // TODO add your handling code here:
  

    }//GEN-LAST:event_image_coverMouseClicked

    private void jButton1_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_add1ActionPerformed

    private void jButton1_add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add2ActionPerformed
        // TODO add your handling code here:
            String path = func.selectImage();
            func.displayImageChoose(image_cover.getWidth(), image_cover.getHeight(), path, image_cover);
            
            imagePath = func.selectImage();
        
        
    }//GEN-LAST:event_jButton1_add2ActionPerformed

    private void book_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_priceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AuthorList aut_list = new AuthorList();
       aut_list.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void book_genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_genreActionPerformed
        // TODO add your handling code here:
        try{
          int genreId = genreMap.get(book_genre.getSelectedItem().toString());
          genre_id.setText(String.valueOf(genreId));
        }catch(Exception e)
        {
            System.out.println("Error from j-comboBox ActionPerform" + e.getMessage());
        }
    }//GEN-LAST:event_book_genreActionPerformed

    private void jButton1_add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add3ActionPerformed
        // TODO add your handling code here:
        Book_ID.setText("");
        Book_name.setText("");
        book_auth.setText("");
        genre_id.setText("ID");
        book_publisher.setText("");
        book_Quantity.setValue(0);
        book_genre.setSelectedIndex(0);
        book_price.setText("");
        book_description.setText("");
        jDateChooser_recieve.setDate(new java.util.Date());
        
        image_cover.setIcon(null);
    }//GEN-LAST:event_jButton1_add3ActionPerformed

    public static void setAuthorData(int id, String fullname){
        book_auth.setText(fullname);
        id_auth = id;
        
    }
    
    //function to verify the required fields 
    public boolean verify()
    {
        if(Book_ID.getText().equals("") || Book_name.getText().equals("")||
           book_auth.getText().equals("") || book_price.getText().equals("") ||
           genre_id.getText().equals("ID")){
            return false;
        }else{
            return true;
        }
    }
    
public void fillJcomboBoxWithGenre(){
    for(String genreName : genreMap.keySet())
    {
        book_genre.addItem(genreName);
    }    
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Book_ID;
    private javax.swing.JTextField Book_name;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Title_Authors;
    private javax.swing.JSpinner book_Quantity;
    public static javax.swing.JTextField book_auth;
    private javax.swing.JTextArea book_description;
    private javax.swing.JComboBox<String> book_genre;
    private javax.swing.JTextField book_price;
    private javax.swing.JTextField book_publisher;
    private javax.swing.JLabel genre_id;
    private javax.swing.JLabel image_cover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_add;
    private javax.swing.JButton jButton1_add1;
    private javax.swing.JButton jButton1_add2;
    private javax.swing.JButton jButton1_add3;
    private com.toedter.calendar.JDateChooser jDateChooser_recieve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
