/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centre_libraly;


import Java_class.Authors;
import Java_class.Member;
import Java_class.function_java;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class AuthorList extends javax.swing.JFrame {

    function_java func = new function_java();
    /**
     * Creates new form MannaegBooks
     */
    Java_class.Authors AuthorInstance = new Java_class.Authors();
    public String typeForm = "";
    
    public AuthorList() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(0,153,153));
        MainPanel.setBorder(panelHeaderBorder);
        function_java.customTableHeader(Jtable_Authorlist, new Color(42, 187, 155), 14);
        
        func.displayImage(50, 50, "image/writer.png", Title_Authors);
        Jtable_Authorlist();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Title_Authors = new javax.swing.JLabel();
        jLabel1_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1_add = new javax.swing.JButton();
        Value_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_Authorlist = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        Title_Authors.setBackground(new java.awt.Color(0, 153, 153));
        Title_Authors.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_Authors.setForeground(new java.awt.Color(255, 255, 255));
        Title_Authors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Authors.setText(" Author list");
        Title_Authors.setOpaque(true);

        jLabel1_exit.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_exit.setText("x");
        jLabel1_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_exit.setOpaque(true);
        jLabel1_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_exitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Enter name :");
        jLabel2.setToolTipText("");

        jButton1_add.setText("search");
        jButton1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addActionPerformed(evt);
            }
        });

        Jtable_Authorlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Jtable_Authorlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtable_AuthorlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable_Authorlist);

        jButton1.setText("confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Title_Authors, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Value_search, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title_Authors, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Value_search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1_add))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 662, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jLabel1_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_exitMouseClicked
        // TODO add your handling code here:
        DasboardForm dash  = new DasboardForm();
        dash.displayCount();
        this.dispose();
        
    }//GEN-LAST:event_jLabel1_exitMouseClicked

    private void jButton1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addActionPerformed
        String value_search = Value_search.getText();
        String query = "select * from Member where firstname = '"+value_search+"'";
        ;
    }//GEN-LAST:event_jButton1_addActionPerformed

    private void Jtable_AuthorlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtable_AuthorlistMouseClicked
        //display selected member in table
        
    }//GEN-LAST:event_Jtable_AuthorlistMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = Jtable_Authorlist.getSelectedRow();
        int id = (int) Jtable_Authorlist.getValueAt(index, 0);
       String firstName = Jtable_Authorlist.getValueAt(index, 1).toString();
       String lastName = Jtable_Authorlist.getValueAt(index, 2).toString();

       String fullName = firstName + " " + lastName;
       
       if(typeForm.equals("edit"))
           EditBookForm.setAuthorData(id, fullName);
       else
           AddBookForm.setAuthorData(id, fullName);
       
       
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

        public void Jtable_Authorlist(){
        ArrayList<Authors> datalist = Authors.AuthorList();
        
        String[] colNames = {"ID", "Name", "Lastname", "Expertise", "about"};
        
        Object[][] Rows = new Object[datalist.size()][colNames.length];
        
        for(int i = 0; i<datalist.size(); i++)
        {
            Rows[i][0] = datalist.get(i).getId();
            Rows[i][1] = datalist.get(i).getName();
            Rows[i][2] = datalist.get(i).getLastName();
            Rows[i][3] = datalist.get(i).getFieldOFexpertise();
            Rows[i][4] = datalist.get(i).getAbout();
        }
        
        DefaultTableModel model = new DefaultTableModel(Rows, colNames);
        Jtable_Authorlist.setModel(model);
    }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Jtable_Authorlist;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Title_Authors;
    private javax.swing.JTextField Value_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
