/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centre_libraly;

import Java_class.BooksManage;
import Java_class.Borrow_book;
import Java_class.function_java;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class bookList_and_remove extends javax.swing.JFrame {

    function_java func = new function_java();
    /**
     * Creates new form MannaegBooks
     */
    Java_class.Authors AuthorInstance = new Java_class.Authors();
    
    public bookList_and_remove() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(0,153,153));
        MainPanel.setBorder(panelHeaderBorder);
        function_java.customTableHeader(Jtable_list, new Color(42, 187, 155), 14);
        func.displayImage(50, 50, "image/book_head.png", title_book);
        Jtable_booklist();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        title_book = new javax.swing.JLabel();
        jLabel1_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1_add = new javax.swing.JButton();
        Value_search = new javax.swing.JTextField();
        jLabel3_enterName2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_list = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_book.setBackground(new java.awt.Color(0, 153, 153));
        title_book.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title_book.setForeground(new java.awt.Color(255, 255, 255));
        title_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_book.setText(" Book list & Delete");
        title_book.setOpaque(true);
        MainPanel.add(title_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 588, 52));

        jLabel1_exit.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_exit.setText("x");
        jLabel1_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_exit.setOpaque(true);
        jLabel1_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_exitMouseClicked(evt);
            }
        });
        MainPanel.add(jLabel1_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 0, 58, 52));

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Enter ID:");
        jLabel2.setToolTipText("");
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 93, -1, -1));

        jButton1_add.setText("search");
        jButton1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 94, 90, -1));
        MainPanel.add(Value_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 94, 408, 23));

        jLabel3_enterName2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3_enterName2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3_enterName2.setText("please! enter member's id (n digit)");
        jLabel3_enterName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_enterName2MouseClicked(evt);
            }
        });
        MainPanel.add(jLabel3_enterName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 123, -1, -1));
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 346, -1, -1));

        Jtable_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Jtable_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtable_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtable_list);

        MainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 148, 568, 318));

        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 499, 216, -1));

        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 499, 216, -1));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 543));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jLabel1_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jLabel1_exitMouseClicked

    private void jButton1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addActionPerformed
        String value_search = Value_search.getText();
        String query = "select * from Member where firstname = '"+value_search+"'";
        
    }//GEN-LAST:event_jButton1_addActionPerformed

    private void jLabel3_enterName2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_enterName2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3_enterName2MouseClicked

    private void Jtable_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtable_listMouseClicked
        //display selected member in table
        int index = Jtable_list.getSelectedRow();
        String id = Jtable_list.getValueAt(index, 0).toString();
        Value_search.setText(id);
    }//GEN-LAST:event_Jtable_listMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = Jtable_list.getSelectedRow();
        String id = Jtable_list.getValueAt(index, 0).toString();
        System.out.println(id);
        Borrow_book.DeleteBorrow(id);
        BooksManage.DeleteData(id);
        
        Jtable_booklist();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

        public void Jtable_booklist(){
        ArrayList<BooksManage> datalist = BooksManage.BookList();
        
        String[] colNames = {"ID", "Book", "Author", "Genre", "publisher","Quantity", "price", "date-recieve", "description"};
        
        Object[][] Rows = new Object[datalist.size()][colNames.length];
        
        for(int i = 0; i<datalist.size(); i++)
        {
            Rows[i][0] = datalist.get(i).getId();
            Rows[i][1] = datalist.get(i).getB_name();
            Rows[i][2] = datalist.get(i).getB_Authors();
            Rows[i][3] = datalist.get(i).getB_Genre();
            Rows[i][4] = datalist.get(i).getPublisher();
            Rows[i][5] = datalist.get(i).getQuantity();
            Rows[i][6] = datalist.get(i).getPrice();
            Rows[i][7] = datalist.get(i).getDate_recieve();
            Rows[i][8] = datalist.get(i).getDescription();
            
        }
        
        DefaultTableModel model = new DefaultTableModel(Rows, colNames);
        Jtable_list.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Jtable_list;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField Value_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_add;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_enterName2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title_book;
    // End of variables declaration//GEN-END:variables
}
