/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centre_libraly;


import Java_class.BooksManage;
import Java_class.Borrow_book;
import Java_class.Member;
import Java_class.function_java;
import java.awt.Color;
import java.awt.HeadlessException;
import java.lang.System.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class BorrowForm extends javax.swing.JFrame {
    
    static String imagePath = "";
    static int id_auth;
    boolean Book_exist = false;
    boolean Member_exist = false;
    
    
    Member member = new Member();
    function_java func = new function_java();
    BooksManage book = new BooksManage();
    Borrow_book borrow = new Borrow_book();
    

    
    /**
     * Creates new form MannaegBooks
     */
    Java_class.Authors AuthorInstance = new Java_class.Authors();
    
    public BorrowForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(0,153,153));
        MainPanel.setBorder(panelHeaderBorder);
        
        func.displayImage(50, 50, "image/book_head.png", Title_book);

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Title_book = new javax.swing.JLabel();
        jLabel1_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1_add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1_add1 = new javax.swing.JButton();
        book_name = new javax.swing.JLabel();
        return_date = new com.toedter.calendar.JDateChooser();
        member_id = new javax.swing.JTextField();
        book_id = new javax.swing.JTextField();
        label_available = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        borrow_date = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jButton1_add4 = new javax.swing.JButton();
        jButton1_add5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Member_name = new javax.swing.JLabel();
        jButton1_add6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_book.setBackground(new java.awt.Color(0, 153, 153));
        Title_book.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_book.setForeground(new java.awt.Color(255, 255, 255));
        Title_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_book.setText("Borrow Book");
        Title_book.setOpaque(true);
        MainPanel.add(Title_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 52));

        jLabel1_exit.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_exit.setText("x");
        jLabel1_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_exit.setOpaque(true);
        jLabel1_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_exitMouseClicked(evt);
            }
        });
        MainPanel.add(jLabel1_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 58, 52));

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Return Date:");
        jLabel2.setToolTipText("");
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jButton1_add.setText("search Member");
        jButton1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 120, 30));
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 576, -1, -1));

        jLabel4.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("Book's ID:");
        jLabel4.setToolTipText("");
        MainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 99, -1, -1));

        jLabel9.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel9.setToolTipText("");
        MainPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jButton1_add1.setText("CANCEL");
        jButton1_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add1ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 90, 34));

        book_name.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        book_name.setText("Book:");
        book_name.setToolTipText("");
        MainPanel.add(book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));
        MainPanel.add(return_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 210, -1));
        MainPanel.add(member_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 200, 30));
        MainPanel.add(book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, 30));

        label_available.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_available.setForeground(new java.awt.Color(255, 51, 0));
        label_available.setText("yes / no");
        MainPanel.add(label_available, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Member's ID:");
        jLabel5.setToolTipText("");
        MainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        MainPanel.add(borrow_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 210, -1));

        jLabel6.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel6.setText("Issue Date:");
        jLabel6.setToolTipText("");
        MainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jButton1_add4.setText("SAVE");
        jButton1_add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add4ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 110, 34));

        jButton1_add5.setText("search Book");
        jButton1_add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add5ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 120, 30));

        jLabel10.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel10.setText("Is This available:");
        jLabel10.setToolTipText("");
        MainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        Member_name.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        Member_name.setText("Name:");
        Member_name.setToolTipText("");
        MainPanel.add(Member_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jButton1_add6.setText("CLEAR");
        jButton1_add6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add6ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 110, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jLabel1_exitMouseClicked

    
    private void jButton1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addActionPerformed
        int id = Integer.parseInt(member_id.getText());
        
        try{
            Member selectedMember = Member.getMemberById(id);
            if(selectedMember != null){
                Member_name.setText(selectedMember.getFname()+" " + selectedMember.getLname());
                //set Member exist to true
                Member_exist = true;
                
                
            }else{
                JOptionPane.showMessageDialog(null, "the Member with this id isn't found");
            }
                    
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1_addActionPerformed

    private void jButton1_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_add1ActionPerformed

    private void jButton1_add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add4ActionPerformed
        // TODO add your handling code here:
        
        // check whether the book and Member exist in database
        String B_id = book_id.getText();
        if(Book_exist == false){
            JOptionPane.showMessageDialog(null, "you need to check whether Book exist", "not found", 2);
        }else if(Member_exist == false){
            JOptionPane.showMessageDialog(null, "you need to check whether Member exist", "not found", 2);
        }else if(!borrow.checkBookAvailable(B_id))
        try{
        
        int M_id = Integer.parseInt(member_id.getText());
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String bor_date = dateFormat.format(borrow_date.getDate());
        String re_date = dateFormat.format(return_date.getDate());
        String state = "issue";
        Date IssDate = dateFormat.parse(bor_date);
        Date rtnDate = dateFormat.parse(re_date);
        if(rtnDate.before(IssDate)){
            JOptionPane.showMessageDialog(null, "the return date must be after the borrow date", "invalid date", 2);
        }else{
            Borrow_book.addBorrow(B_id, M_id, state, bor_date, re_date); 
        }
       
        }catch(NumberFormatException | HeadlessException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "select borrow date & return date", "select date", 2);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error on date", "select date", 2);
        }
    }//GEN-LAST:event_jButton1_add4ActionPerformed

    private void jButton1_add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add5ActionPerformed
        // TODO add your handling code here:
        String B_id = book_id.getText();
        BooksManage selectedBook = book.searchByID(B_id);
        try{
            if(selectedBook != null){
                
            book_name.setText("  "+ "borrow '"+selectedBook.getB_name()+ "'");
            
            // set the book_exist to true            
            Book_exist = true;
            
            if(borrow.checkBookAvailable(B_id)){
               label_available.setText("yes");
               label_available.setForeground(Color.green);
            }else{
                label_available.setText("no");
                label_available.setForeground(Color.red);
            }
            }else{
                JOptionPane.showMessageDialog(null, "this book isn't exist", "not found", 2);
                label_available.setText("YES-or-NO");
            }
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1_add5ActionPerformed

    private void jButton1_add6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_add6ActionPerformed
  // function to check whether is the book is available on database
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Member_name;
    private javax.swing.JLabel Title_book;
    private javax.swing.JTextField book_id;
    private javax.swing.JLabel book_name;
    private com.toedter.calendar.JDateChooser borrow_date;
    private javax.swing.JButton jButton1_add;
    private javax.swing.JButton jButton1_add1;
    private javax.swing.JButton jButton1_add4;
    private javax.swing.JButton jButton1_add5;
    private javax.swing.JButton jButton1_add6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_available;
    private javax.swing.JTextField member_id;
    private com.toedter.calendar.JDateChooser return_date;
    // End of variables declaration//GEN-END:variables
}
