/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centre_libraly;


import Java_class.Authors;
import Java_class.BooksManage;
import Java_class.Genres;
import Java_class.Member;
import Java_class.function_java;
import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author HP
 */
public class EditBookForm extends javax.swing.JFrame {
    
    static String imagePath = "";
    static int id_auth;
    
    Member member = new Member();
    function_java func = new function_java();
    Genres genre = new Genres();
    HashMap<String, Integer> genreMap = genre.getGenreMap();
    /**
     * Creates new form MannaegBooks
     */
    Java_class.Authors AuthorInstance = new Java_class.Authors();
    
    public EditBookForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(0,153,153));
        MainPanel.setBorder(panelHeaderBorder);
        
        func.displayImage(50, 50, "image/book_head.png", Title_book);
        
        //table to show data
         fillJcomboBoxWithGenre();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Title_book = new javax.swing.JLabel();
        jLabel1_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1_add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Book_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        book_publisher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        image_cover = new javax.swing.JLabel();
        Book_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        book_description = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        book_genre = new javax.swing.JComboBox<>();
        book_Quantity = new javax.swing.JSpinner();
        jButton1_add2 = new javax.swing.JButton();
        book_price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        book_auth = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser_recieve = new com.toedter.calendar.JDateChooser();
        genre_id = new javax.swing.JLabel();
        jButton1_add3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1_add4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_book.setBackground(new java.awt.Color(0, 153, 153));
        Title_book.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_book.setForeground(new java.awt.Color(255, 255, 255));
        Title_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_book.setText("Edit Book");
        Title_book.setOpaque(true);
        MainPanel.add(Title_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 821, 52));

        jLabel1_exit.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_exit.setText("x");
        jLabel1_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_exit.setOpaque(true);
        jLabel1_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_exitMouseClicked(evt);
            }
        });
        MainPanel.add(jLabel1_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 0, 58, 52));

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Book's Name");
        jLabel2.setToolTipText("");
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jButton1_add.setText("Edit");
        jButton1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 522, 225, 34));

        jLabel3.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Authors:");
        jLabel3.setToolTipText("");
        MainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        Book_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_nameActionPerformed(evt);
            }
        });
        MainPanel.add(Book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 245, 23));

        jLabel5.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Genre:");
        jLabel5.setToolTipText("");
        MainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        book_publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_publisherActionPerformed(evt);
            }
        });
        MainPanel.add(book_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 285, 227, 23));

        jLabel6.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel6.setText("Publisher:");
        jLabel6.setToolTipText("");
        MainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 284, -1, -1));
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        image_cover.setBackground(new java.awt.Color(204, 204, 204));
        image_cover.setOpaque(true);
        image_cover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image_coverMouseClicked(evt);
            }
        });
        MainPanel.add(image_cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 157, 105));

        Book_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_IDActionPerformed(evt);
            }
        });
        MainPanel.add(Book_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 79, 168, 25));

        jLabel4.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("search by id");
        jLabel4.setToolTipText("");
        MainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 79, -1, -1));

        jLabel7.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel7.setText("Quantity:");
        jLabel7.setToolTipText("");
        MainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 346, -1, -1));

        jLabel9.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel9.setText("Date's Recieve:");
        jLabel9.setToolTipText("");
        MainPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 462, -1, -1));

        book_description.setColumns(20);
        book_description.setRows(5);
        jScrollPane1.setViewportView(book_description);

        MainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 375, 131));

        jLabel10.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel10.setText("Book's Cover");
        jLabel10.setToolTipText("");
        MainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 259, -1, -1));

        jLabel11.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel11.setText("Book's decription");
        jLabel11.setToolTipText("");
        MainPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 79, -1, -1));

        book_genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default" }));
        book_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_genreActionPerformed(evt);
            }
        });
        MainPanel.add(book_genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 232, 170, -1));
        MainPanel.add(book_Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 348, 157, -1));

        jButton1_add2.setBackground(new java.awt.Color(51, 51, 51));
        jButton1_add2.setForeground(new java.awt.Color(51, 51, 51));
        jButton1_add2.setText("select picture");
        jButton1_add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add2ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 423, 136, -1));

        book_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_priceActionPerformed(evt);
            }
        });
        MainPanel.add(book_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 408, 193, 23));

        jLabel8.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("Price:");
        jLabel8.setToolTipText("");
        MainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 407, -1, -1));

        book_auth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_authActionPerformed(evt);
            }
        });
        MainPanel.add(book_auth, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 170, -1));

        jButton1.setText("select author");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 179, -1, -1));
        MainPanel.add(jDateChooser_recieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 465, 128, -1));

        genre_id.setText("ID");
        MainPanel.add(genre_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 232, 40, -1));

        jButton1_add3.setText("Clear");
        jButton1_add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add3ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 522, 225, 34));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("search");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 78, 92, 25));

        jButton1_add4.setText("Clear");
        jButton1_add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add4ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 522, 225, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jLabel1_exitMouseClicked

    
    private void jButton1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addActionPerformed
         
        if(!verify()){
            JOptionPane.showMessageDialog(null, "data is not valid", "invalid", 0);
       }else{
           String id  = Book_ID.getText();
           String name = Book_name.getText();
         int Author = id_auth;
         int genre = Integer.parseInt(genre_id.getText());
         String publisher = book_publisher.getText();
         int Quantity = Integer.parseInt(book_Quantity.getValue().toString());
         double price = Double.parseDouble(book_price.getText());
         String description = book_description.getText();
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
         String date_recieve = dateFormat.format(jDateChooser_recieve.getDate());
         
         
            try {
                byte[] img = Files.readAllBytes(Paths.get(imagePath));
                BooksManage.UpdateBook(id, name, 0, 0, publisher, Quantity, price, date_recieve, description, img);
            } catch (IOException ex) {
                Logger.getLogger(EditBookForm.class.getName()).log(Level.SEVERE, null, ex);
            }catch(NumberFormatException e){
                System.out.println("numberformate is getting Error");
            }
       }
    }//GEN-LAST:event_jButton1_addActionPerformed

    private void book_publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_publisherActionPerformed

    private void image_coverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_coverMouseClicked
        // TODO add your handling code here:
  

    }//GEN-LAST:event_image_coverMouseClicked

    private void jButton1_add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add2ActionPerformed
        // TODO add your handling code here:
            String path = func.selectImage();
            func.displayImage(image_cover.getWidth(), image_cover.getHeight(), path, image_cover);
            
            imagePath = func.selectImage();
        
        
    }//GEN-LAST:event_jButton1_add2ActionPerformed

    private void book_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_priceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AuthorList aut_list = new AuthorList();
        aut_list.typeForm = "edit";
       aut_list.setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void book_genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_genreActionPerformed
        // TODO add your handling code here:
        try{
          int genreId = genreMap.get(book_genre.getSelectedItem().toString());
          genre_id.setText(String.valueOf(genreId));
        }catch(Exception e)
        {
            System.out.println("Error from j-comboBox ActionPerform" + e.getMessage());
        }
    }//GEN-LAST:event_book_genreActionPerformed

    private void jButton1_add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add3ActionPerformed
        // TODO add your handling code here:
        Book_ID.setText("");
        Book_name.setText("");
        book_auth.setText("");
        genre_id.setText("ID");
        book_publisher.setText("");
        book_Quantity.setValue(0);
        book_genre.setSelectedIndex(0);
        book_price.setText("");
        book_description.setText("");
        jDateChooser_recieve.setDate(new java.util.Date());
        
        image_cover.setIcon(null);
    }//GEN-LAST:event_jButton1_add3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(Book_ID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "data can't be empty", "empty no allowe", 2);
        }else{
          try{
           String ID =  Book_ID.getText();
           BooksManage book = BooksManage.searchByID(ID);
        
           Book_name.setText(book.getB_name());
           book_publisher.setText(book.getPublisher());
           book_description.setText(book.getDescription());
           book_price.setText(Double.toString(book.getPrice()));
           id_auth = book.getB_Authors();
           genre_id.setText(String.valueOf(book.getB_Genre()));
           Date date_recieve = new SimpleDateFormat("yyyy-MM-dd").parse(book.getDate_recieve());
           jDateChooser_recieve.setDate(date_recieve);
           book_Quantity.setValue(book.getQuantity());
           for(Map.Entry<String, Integer> entry : genreMap.entrySet()){
             if(Objects.equals(book.getB_Genre(),entry.getValue() )){
                 book_genre.setSelectedItem(entry.getKey());
            }
         }
         String fullName = (Authors.getAuthorByID(book.getB_Authors())).getName() +
                   (Authors.getAuthorByID(book.getB_Authors())).getLastName();
           book_auth.setText(fullName);
           
           
            byte[] image = book.getCover_image();
            func.displayImageByte(50, 40, image, image_cover);
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, "data with this id isn't exist in the system", "not found", 2);
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Book_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_IDActionPerformed

    private void Book_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_nameActionPerformed

    private void jButton1_add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_add4ActionPerformed

    private void book_authActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_authActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_authActionPerformed

    public static void setAuthorData(int id, String fullname){
        book_auth.setText(fullname);
        id_auth = id;
        
    }
    
    //function to verify the required fields 
    public boolean verify()
    {
        if(Book_ID.getText().equals("") || Book_name.getText().equals("")||
           book_auth.getText().equals("") || book_price.getText().equals("") ||
           genre_id.getText().equals("ID")){
            return false;
        }else{
            return true;
        }
    }
    
public void fillJcomboBoxWithGenre(){
    for(String genreName : genreMap.keySet())
    {
        book_genre.addItem(genreName);
    }    
}
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Book_ID;
    private javax.swing.JTextField Book_name;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Title_book;
    private javax.swing.JSpinner book_Quantity;
    public static javax.swing.JTextField book_auth;
    private javax.swing.JTextArea book_description;
    private javax.swing.JComboBox<String> book_genre;
    private javax.swing.JTextField book_price;
    private javax.swing.JTextField book_publisher;
    private javax.swing.JLabel genre_id;
    private javax.swing.JLabel image_cover;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_add;
    private javax.swing.JButton jButton1_add2;
    private javax.swing.JButton jButton1_add3;
    private javax.swing.JButton jButton1_add4;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser_recieve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
