/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centre_libraly;


import Java_class.Genres;
import Java_class.function_java;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class Manage_Gemres extends javax.swing.JFrame {

    function_java func = new function_java();
    /**
     * Creates new form Manage_Gemres
     */
    Genres genresInstance = new Genres();
    
    public Manage_Gemres() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        function_java.customTable(jTable1_genres);
        
        function_java.customTableHeader(jTable1_genres, new Color(42, 187, 155), 14);
        
        jLabel3_enterName.setVisible(false);
       
        func.displayImage(50, 50, "image/genres.png", Title_genre);
        
        Border border_Genre = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(0,153,153));
        Genre_panel.setBorder(border_Genre);
        //table to show data
        Jtable_genres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genre_panel = new javax.swing.JPanel();
        Title_genre = new javax.swing.JLabel();
        jLabel1_exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2_name = new javax.swing.JTextField();
        jButton1_add = new javax.swing.JButton();
        jButton2_edit = new javax.swing.JButton();
        jButton3_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_genres = new javax.swing.JTable();
        jLabel3_enterName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Genre_panel.setBackground(new java.awt.Color(255, 255, 255));

        Title_genre.setBackground(new java.awt.Color(0, 153, 153));
        Title_genre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_genre.setForeground(new java.awt.Color(255, 255, 255));
        Title_genre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_genre.setText("Manage Books Genres");
        Title_genre.setOpaque(true);

        jLabel1_exit.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_exit.setText("x");
        jLabel1_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_exit.setOpaque(true);
        jLabel1_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_exitMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Defago Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        jLabel2.setToolTipText("");

        jButton1_add.setText("Add");
        jButton1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addActionPerformed(evt);
            }
        });

        jButton2_edit.setText("Edit");
        jButton2_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_editActionPerformed(evt);
            }
        });

        jButton3_delete.setText("Delete");
        jButton3_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_deleteActionPerformed(evt);
            }
        });

        jTable1_genres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_genres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_genresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_genres);

        jLabel3_enterName.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3_enterName.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3_enterName.setText("please! enter your name");
        jLabel3_enterName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_enterNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Genre_panelLayout = new javax.swing.GroupLayout(Genre_panel);
        Genre_panel.setLayout(Genre_panelLayout);
        Genre_panelLayout.setHorizontalGroup(
            Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Genre_panelLayout.createSequentialGroup()
                .addComponent(Title_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Genre_panelLayout.createSequentialGroup()
                .addGroup(Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Genre_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3_enterName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Genre_panelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        Genre_panelLayout.setVerticalGroup(
            Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Genre_panelLayout.createSequentialGroup()
                .addGroup(Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Title_genre, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabel1_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Genre_panelLayout.createSequentialGroup()
                        .addGroup(Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3_enterName)
                        .addGap(37, 37, 37)
                        .addGroup(Genre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3_delete)
                            .addComponent(jButton2_edit)
                            .addComponent(jButton1_add)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(Genre_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 636, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jLabel1_exitMouseClicked

    private void jButton1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addActionPerformed
       
        String name = jTextField2_name.getText();
        
        if(name.isEmpty()){
            jLabel3_enterName.setVisible(true);
        }else{
            try{
                genresInstance.addGenres(name);
                
                
                Jtable_genres();
                
            }catch(NumberFormatException ex){
                 JOptionPane.showMessageDialog(null,"invalid genres id", "error", 0);
            }
            
        }
    }//GEN-LAST:event_jButton1_addActionPerformed

    private void jButton2_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_editActionPerformed
        // TODO add your handling code here:
        int Id = Integer.valueOf(jTextField1_id.getText());
        String name = jTextField2_name.getText();
        
        if(name.isEmpty()){
            jLabel3_enterName.setVisible(true);
            
        }else{
            genresInstance.editGenres(Id, name);
            
            Jtable_genres();
        }
    }//GEN-LAST:event_jButton2_editActionPerformed

    private void jButton3_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_deleteActionPerformed
        // TODO add your handling code here:
        
        try{
            int id = Integer.parseInt(jTextField1_id.getText());
            genresInstance.DeleteGenres(id);
            Jtable_genres();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "invalid genres "+ ex.getMessage(), "error", 0);
        }
    }//GEN-LAST:event_jButton3_deleteActionPerformed

    private void jTable1_genresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_genresMouseClicked
        // TODO add your handling code here:
        int index = jTable1_genres.getSelectedRow();
        
        String id = jTable1_genres.getValueAt(index, 0).toString();
        String name = jTable1_genres.getValueAt(index, 1).toString();
        
        jTextField1_id.setText(id);
        jTextField2_name.setText(name);
        this.validate();
    }//GEN-LAST:event_jTable1_genresMouseClicked

    private void jLabel3_enterNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_enterNameMouseClicked
        // TODO add your handling code here:
        
        jLabel3_enterName.setVisible(false);
    }//GEN-LAST:event_jLabel3_enterNameMouseClicked

    
    
    public void Jtable_genres(){
        ArrayList<Genres> genresList = Genres.genreList();
        
        String[] colNames = {"ID", "NAME"};
        
        Object[][] Rows = new Object[genresList.size()][colNames.length];
        
        for(int i = 0; i<genresList.size(); i++)
        {
            Rows[i][0] = genresList.get(i).getId();
            Rows[i][1] = genresList.get(i).getName();
        }
        
        DefaultTableModel model = new DefaultTableModel(Rows, colNames);
        jTable1_genres.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Genre_panel;
    private javax.swing.JLabel Title_genre;
    private javax.swing.JButton jButton1_add;
    private javax.swing.JButton jButton2_edit;
    private javax.swing.JButton jButton3_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_enterName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_genres;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField2_name;
    // End of variables declaration//GEN-END:variables
}
