/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centre_libraly;


import Java_class.Member;
import Java_class.function_java;
import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author HP
 */
public class memberForm extends javax.swing.JFrame {

    function_java func = new function_java();
    /**
     * Creates new form MannaegBooks
     */
    Java_class.Authors AuthorInstance = new Java_class.Authors();
    
    public memberForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(0,153,153));
        MainPanel.setBorder(panelHeaderBorder);
        func.displayImage(50, 40, "image/team.png", Title_Member);

        jLabel3_enterName.setVisible(false);
        
        //table to show data
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Title_Member = new javax.swing.JLabel();
        jLabel1_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2_Lname = new javax.swing.JTextField();
        jButton1_add = new javax.swing.JButton();
        jLabel3_enterName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2_Fname = new javax.swing.JTextField();
        jTextField2_major = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3_enterName1 = new javax.swing.JLabel();
        jLabel3_enterName2 = new javax.swing.JLabel();
        jTextField2_phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        genderbox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        image_icons = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Member.setBackground(new java.awt.Color(0, 153, 153));
        Title_Member.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_Member.setForeground(new java.awt.Color(255, 255, 255));
        Title_Member.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Member.setText("Add Member");
        Title_Member.setOpaque(true);
        MainPanel.add(Title_Member, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 462, 52));

        jLabel1_exit.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_exit.setText("x");
        jLabel1_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_exit.setOpaque(true);
        jLabel1_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_exitMouseClicked(evt);
            }
        });
        MainPanel.add(jLabel1_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 0, 58, 52));

        jLabel2.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Name:");
        jLabel2.setToolTipText("");
        MainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 93, -1, -1));
        MainPanel.add(jTextField2_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 173, 271, 23));

        jButton1_add.setText("Add");
        jButton1_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_addActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 568, 225, 33));

        jLabel3_enterName.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3_enterName.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3_enterName.setText("please! enter your name");
        jLabel3_enterName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_enterNameMouseClicked(evt);
            }
        });
        MainPanel.add(jLabel3_enterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 315, 129, -1));

        jLabel3.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Lastname:");
        jLabel3.setToolTipText("");
        MainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 172, -1, -1));
        MainPanel.add(jTextField2_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 94, 271, 23));

        jTextField2_major.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_majorActionPerformed(evt);
            }
        });
        MainPanel.add(jTextField2_major, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 286, 271, 23));

        jLabel5.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Major:");
        jLabel5.setToolTipText("");
        MainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 285, -1, -1));

        jLabel3_enterName1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3_enterName1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3_enterName1.setText("please! enter your name");
        jLabel3_enterName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_enterName1MouseClicked(evt);
            }
        });
        MainPanel.add(jLabel3_enterName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 202, 129, -1));

        jLabel3_enterName2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3_enterName2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3_enterName2.setText("please! enter your name");
        jLabel3_enterName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_enterName2MouseClicked(evt);
            }
        });
        MainPanel.add(jLabel3_enterName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 123, 129, -1));

        jTextField2_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_phoneActionPerformed(evt);
            }
        });
        MainPanel.add(jTextField2_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 370, 271, 23));

        jLabel6.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel6.setText("Phone:");
        jLabel6.setToolTipText("");
        MainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 369, -1, -1));
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        MainPanel.add(genderbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 236, 105, -1));

        jLabel7.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel7.setText("Gender");
        jLabel7.setToolTipText("");
        MainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 234, -1, -1));

        image_icons.setBackground(new java.awt.Color(204, 204, 204));
        image_icons.setOpaque(true);
        image_icons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image_iconsMouseClicked(evt);
            }
        });
        MainPanel.add(image_icons, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 425, 145, 105));

        jLabel8.setText("click above to select profile");
        MainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 536, -1, -1));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jLabel1_exitMouseClicked

    private void jButton1_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_addActionPerformed
   
        String Fname = jTextField2_Fname.getText();
        String Lname = jTextField2_Lname.getText();
        String gender = genderbox.getSelectedItem().toString();
        String major = jTextField2_major.getText();
        int phonenum = Integer.parseInt(jTextField2_phone.getText());
        String picture = image_icons.getText();
        
       
        
        if(Fname.isEmpty() && Lname.isEmpty()){
            jLabel3_enterName.setVisible(true);   
        }else{
            /*byte[] img = null
            if(imagePath != null){
            Path path = Path.get(img);
            img = Files.readAllBytes(path);
            }
            */
            Member member = new Member();
            
            member.addMemeber(Fname, Lname,gender, major,phonenum,picture);
           
        }
    }//GEN-LAST:event_jButton1_addActionPerformed

    private void jLabel3_enterNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_enterNameMouseClicked
        // TODO add your handling code here:
        
        jLabel3_enterName.setVisible(false);
    }//GEN-LAST:event_jLabel3_enterNameMouseClicked

    private void jTextField2_majorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_majorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_majorActionPerformed

    private void jLabel3_enterName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_enterName1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3_enterName1MouseClicked

    private void jLabel3_enterName2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_enterName2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3_enterName2MouseClicked

    private void jTextField2_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_phoneActionPerformed

    private void image_iconsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_iconsMouseClicked
        // TODO add your handling code here:
        JFileChooser filechoose = new JFileChooser();
        filechoose.setDialogTitle("select profile picture");
        
        //when user select to choose the profiel this code will link to folder of image
        filechoose.setCurrentDirectory(new File("c:\\Java_class\\image"));
        
        FileNameExtensionFilter extentionFilter = new FileNameExtensionFilter("image",".png",".jpg",".jpeg");
        filechoose.addChoosableFileFilter(extentionFilter);
        
        int fileState = filechoose.showSaveDialog(null);
        
        if(fileState == JFileChooser.APPROVE_OPTION){
            String path = filechoose.getSelectedFile().getAbsolutePath();
            image_icons.setText(path);
        }
    }//GEN-LAST:event_image_iconsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Title_Member;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JLabel image_icons;
    private javax.swing.JButton jButton1_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_enterName;
    private javax.swing.JLabel jLabel3_enterName1;
    private javax.swing.JLabel jLabel3_enterName2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2_Fname;
    private javax.swing.JTextField jTextField2_Lname;
    private javax.swing.JTextField jTextField2_major;
    private javax.swing.JTextField jTextField2_phone;
    // End of variables declaration//GEN-END:variables
}
