/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centre_libraly;


import Java_class.BooksManage;
import Java_class.Borrow_book;
import Java_class.Member;
import Java_class.function_java;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class ReturnForm extends javax.swing.JFrame {
    
    static String imagePath = "";
    static int id_auth;
    boolean Book_exist = false;
    boolean Member_exist = false;
    
    
    Member member = new Member();
    function_java func = new function_java();
    BooksManage book = new BooksManage();
    Borrow_book borrow = new Borrow_book();
    

    
    /**
     * Creates new form MannaegBooks
     */
    Java_class.Authors AuthorInstance = new Java_class.Authors();
   
    public ReturnForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(0,153,153));
        MainPanel.setBorder(panelHeaderBorder);
        func.displayImage(50, 50, "image/book_head.png", Title_Book);
        
     groupbutton.add(RadioButton1);
     groupbutton.add(RadioButton2);
      
     Jtable_Borrow_list();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupbutton = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        Title_Book = new javax.swing.JLabel();
        jLabel1_exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1_add1 = new javax.swing.JButton();
        return_label = new javax.swing.JLabel();
        borrow_id = new javax.swing.JTextField();
        jButton1_add4 = new javax.swing.JButton();
        jButton1_add5 = new javax.swing.JButton();
        Borrow_id = new javax.swing.JLabel();
        book_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        M_name = new javax.swing.JLabel();
        B_name = new javax.swing.JLabel();
        Return_date = new javax.swing.JLabel();
        Borrow_date = new javax.swing.JLabel();
        return_label1 = new javax.swing.JLabel();
        fact_date = new com.toedter.calendar.JDateChooser();
        RadioButton1 = new javax.swing.JRadioButton();
        RadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Borrow = new javax.swing.JTable();
        Member_name1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_Book.setBackground(new java.awt.Color(0, 153, 153));
        Title_Book.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title_Book.setForeground(new java.awt.Color(255, 255, 255));
        Title_Book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Book.setText("Borrow Book");
        Title_Book.setOpaque(true);
        MainPanel.add(Title_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 52));

        jLabel1_exit.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1_exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_exit.setText("x");
        jLabel1_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_exit.setOpaque(true);
        jLabel1_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_exitMouseClicked(evt);
            }
        });
        MainPanel.add(jLabel1_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 0, 58, 52));
        MainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("ຶBorrow's ID:");
        jLabel4.setToolTipText("");
        MainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        jLabel9.setToolTipText("");
        MainPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jButton1_add1.setText("CANCEL");
        jButton1_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add1ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 442, 90, 34));

        return_label.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        return_label.setText("Return date:");
        return_label.setToolTipText("");
        MainPanel.add(return_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 280, -1, -1));
        MainPanel.add(borrow_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 90, 144, 30));

        jButton1_add4.setText("SAVE");
        jButton1_add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add4ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 442, 110, 34));

        jButton1_add5.setText("search Book");
        jButton1_add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_add5ActionPerformed(evt);
            }
        });
        MainPanel.add(jButton1_add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 90, 120, 30));

        Borrow_id.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        Borrow_id.setText("......");
        Borrow_id.setToolTipText("");
        MainPanel.add(Borrow_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        book_label.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        book_label.setText("Book:");
        book_label.setToolTipText("");
        MainPanel.add(book_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        date_label.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        date_label.setText("Borrow's date:");
        date_label.setToolTipText("");
        MainPanel.add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        M_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        M_name.setText("........");
        MainPanel.add(M_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 164, 190, -1));

        B_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        B_name.setText("........");
        MainPanel.add(B_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 204, 190, -1));

        Return_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Return_date.setText("..........");
        MainPanel.add(Return_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 284, 190, -1));

        Borrow_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Borrow_date.setText(".........");
        MainPanel.add(Borrow_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 244, 190, -1));

        return_label1.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        return_label1.setText("return date fact:");
        return_label1.setToolTipText("");
        MainPanel.add(return_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, -1, -1));
        MainPanel.add(fact_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 324, 144, -1));

        RadioButton1.setText(" return");
        MainPanel.add(RadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 362, 93, -1));

        RadioButton2.setText("not yet");
        RadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton2ActionPerformed(evt);
            }
        });
        MainPanel.add(RadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 362, 93, -1));

        jTable_Borrow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Borrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BorrowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Borrow);

        MainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 390));

        Member_name1.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        Member_name1.setText("Name:");
        Member_name1.setToolTipText("");
        MainPanel.add(Member_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        label1.setFont(new java.awt.Font("Defago Noto Sans", 0, 14)); // NOI18N
        label1.setText("ID:");
        label1.setToolTipText("");
        MainPanel.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jLabel1_exitMouseClicked

    
    private void jButton1_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_add1ActionPerformed

    private void jButton1_add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add4ActionPerformed
        // TODO add your handling code here:
        String radioButton = null;
        if(RadioButton1.isSelected() == true){
            radioButton = "Return";
        }else if(RadioButton2.isSelected() == true){
            radioButton = "Borrow";
        }
        int id = Integer.parseInt(Borrow_id.getText());
        
        if(radioButton == null){
            JOptionPane.showMessageDialog(null, "return button is empty", "Invalid", 2);
        }else if(fact_date.getDate() == null){
            JOptionPane.showMessageDialog(null, "you must enter date", "Invalid", 2);
        }else{
            Borrow_book.Return_book(id, radioButton);
        }
        Jtable_Borrow_list();
    }//GEN-LAST:event_jButton1_add4ActionPerformed

    private void jButton1_add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_add5ActionPerformed
        // TODO add your handling code here:
        String B_id = borrow_id.getText();
        BooksManage selectedBook = book.searchByID(B_id);
        try{
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1_add5ActionPerformed

    private void RadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton2ActionPerformed

    private void jTable_BorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BorrowMouseClicked
        // TODO add your handling code here:
        int index = jTable_Borrow.getSelectedRow();
        
        String bor_id = jTable_Borrow.getValueAt(index, 0).toString();
        String book_id = jTable_Borrow.getValueAt(index, 1).toString();
        String Member_id = jTable_Borrow.getValueAt(index, 2).toString();
        String borrow_date = jTable_Borrow.getValueAt(index, 3).toString();
        String return_date = jTable_Borrow.getValueAt(index, 4).toString();
        Borrow_id.setText(bor_id);
        M_name.setText(book_id);
        B_name.setText(Member_id);
        Borrow_date.setText(borrow_date);
        Return_date.setText(return_date);
    }//GEN-LAST:event_jTable_BorrowMouseClicked
   
      public void Jtable_Borrow_list(){
     ArrayList<Borrow_book> member = Borrow_book.Borrow_List();
     
     String[] colName = {"ID","book_id","Member id","status","Borrow date", "return date" };
     
     Object[][] rows = new Object[member.size()][colName.length];
     for(int i =0;i<member.size(); i++){
         rows[i][0] = member.get(i).getId();
         rows[i][1] = member.get(i).getBook_id();
         rows[i][2] = member.get(i).getMember_id();
         rows[i][3] = member.get(i).getStatus();
         rows[i][4] = member.get(i).getBorrow_date();
         rows[i][5] = member.get(i).getReturn_date();
    
     }
     DefaultTableModel model = new DefaultTableModel(rows, colName);
     jTable_Borrow.setModel(model);
     
 }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_name;
    private javax.swing.JLabel Borrow_date;
    private javax.swing.JLabel Borrow_id;
    private javax.swing.JLabel M_name;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Member_name1;
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JRadioButton RadioButton2;
    private javax.swing.JLabel Return_date;
    private javax.swing.JLabel Title_Book;
    private javax.swing.JLabel book_label;
    private javax.swing.JTextField borrow_id;
    private javax.swing.JLabel date_label;
    private com.toedter.calendar.JDateChooser fact_date;
    private javax.swing.ButtonGroup groupbutton;
    private javax.swing.JButton jButton1_add1;
    private javax.swing.JButton jButton1_add4;
    private javax.swing.JButton jButton1_add5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_exit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Borrow;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel return_label;
    private javax.swing.JLabel return_label1;
    // End of variables declaration//GEN-END:variables
}
